"""Initial migration

Revision ID: 054ee61f33a8
Revises: 
Create Date: 2026-02-27 12:04:27.996161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054ee61f33a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='niveau'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formations_id'), 'formations', ['id'], unique=False)
    op.create_index('ix_formations_level', 'formations', ['level'], unique=False)
    op.create_index(op.f('ix_formations_title'), 'formations', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='role'), nullable=False),
    sa.Column('inscription_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.Column('formateur_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('capacite_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('capacite_max >= 1', name='check_capacite_positive'),
    sa.CheckConstraint('date_fin > date_debut', name='check_dates_coherentes'),
    sa.ForeignKeyConstraint(['formateur_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_inscription', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_inscription_user_session')
    )
    op.create_index(op.f('ix_inscriptions_id'), 'inscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_inscriptions_session_id'), 'inscriptions', ['session_id'], unique=False)
    op.create_index(op.f('ix_inscriptions_user_id'), 'inscriptions', ['user_id'], unique=False)
    op.create_index('ix_inscriptions_user_session', 'inscriptions', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inscriptions_user_session', table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_user_id'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_session_id'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_id'), table_name='inscriptions')
    op.drop_table('inscriptions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_formations_title'), table_name='formations')
    op.drop_index('ix_formations_level', table_name='formations')
    op.drop_index(op.f('ix_formations_id'), table_name='formations')
    op.drop_table('formations')
    # ### end Alembic commands ###
