"""add_capacite_minimale_to_sessions

Revision ID: 94f6d886cc28
Revises: 61addc407d05
Create Date: 2026-03-04 10:40:35.230350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f6d886cc28'
down_revision: Union[str, Sequence[str], None] = '61addc407d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('capacite_minimale', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'capacite_minimale')
    # ### end Alembic commands ###
