"""add status to session

Revision ID: b38bf7802471
Revises: 054ee61f33a8
Create Date: 2026-02-27 13:43:55.273023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38bf7802471'
down_revision: Union[str, Sequence[str], None] = '054ee61f33a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_COURS', 'TERMINEE', 'ANNULEE', name='sessionstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'statut')
    # ### end Alembic commands ###
